### ISSUE TITLE
Axes analytiques dans Dext

### ISSUE THREAD

**Issue by AmauryVanEspen** [MyUnisoft/api-partenaires#84]
Bonjour,
l'intégration dans Dext a un point bloquant majeur,
en effet, en connectant MyUnisoft avec Dext, la possibilité d'utiliser les Axes Analytiques, fonctionnalité essentielle de Dext, n'est plus possible, dans la mesure où la descente des axes analytiques depuis MyUnisoft n'est pas conforme.
Pourriez vous m'en dire plus sur comment résoudre ou contourner ce problème ?
Cordialement
Amaury

**Comment by fraxken** [comment]
@AmauryVanEspen

L'intégration avec Dext ne supporte pas l'analytique. À ce jour, il n'y a pas de contournement, sauf en intégrant manuellement via un format d'import commun.

Le sujet est connu, et des développements sont déjà en cours depuis le début de l'année pour proposer une nouvelle version expérimentale de l'intégration utilisant [MAD](https://dev.to/fraxken/designing-myunisoft-next-gen-accounting-apis-1mn).

J'espère avoir les premiers tests avant la fin de l'année (et l'avoir par défaut courant 2025).

**Comment by AmauryVanEspen** [comment]
@fraxken 
Merci de la réponse, 
Un exemple de format commun pour l'intégration manuelle (et la procédure ?) 
Ça serait top
Merci

**Comment by fraxken** [comment]
@AmauryVanEspen Je ne suis pas spécialement expert sur leur format d'export (je sais juste que c'est ce que font certains clients). Je pense qu'un export en CEGID TRA ça devrait être ok.

Je crois qu'on n'a pas encore dans l'interface web, mais FEC+PJ devrait le faire aussi (ça arrive prochaine livraison de mémoire).

**Comment by AmauryVanEspen** [comment]
Bonjour @fraxken 
avec la mise à jour ici : https://help.dext.com/fr/s/article/gerer-son-analytique  peut on espérer que désormais les axes analytiques remontent enfin vers Dext ?
A défaut, etes vous en mesure d'exporter le FEC côté My Unifost afin de se débarrasser de Dext et pouvoir reprendre "le cours normal des activités et de pilotage" ?
Merci
Cordialement
Amaury
